# Generated by Django 4.2.4 on 2023-08-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=70, null=True, verbose_name='productName')),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='color')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('product_category', models.CharField(blank=True, max_length=30, null=True, verbose_name='product_category')),
            ],
        ),
    ]
