# Generated by Django 4.2.4 on 2023-08-12 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.TextField(blank=True, null=True, verbose_name='color_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.color'),
            preserve_default=False,
        ),
    ]
