# Generated by Django 4.2.4 on 2023-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_color_color_name_remove_product_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_Date',
            field=models.DateField(blank=True, null=True, verbose_name='added_Date'),
        ),
    ]
