# Generated by Django 4.2.4 on 2023-08-22 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0006_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('Favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='color_name')),
                ('numberOfProduct', models.IntegerField(blank=True, null=True, verbose_name='number_of_products')),
                ('product', models.ManyToManyField(related_name='FavoriteProduct', to='Products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserInstance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
